<script lang="ts">
  // The canonical disclaimer wording, in ONE place so the first-run notice
  // (DisclaimerNotice.svelte) and the always-available copy (Operations → Logs)
  // never drift. `heading` controls the semantic level of the title so the modal
  // can label itself while the inline copy nests under an existing <h3>.
  let { heading = "h2" }: { heading?: "h2" | "h3" } = $props();
</script>

<div class="disclaimer">
  <svelte:element this={heading} class="disc-title" id="disclaimer-title">
    Before you start
  </svelte:element>
  <p class="disc-intro">
    millfolio is a personal project, provided “as is,” with no warranty and no
    liability (see the
    <a href="https://github.com/millfolio/millfolio/blob/main/LICENSE" target="_blank" rel="noopener">Apache-2.0 LICENSE</a>).
    By using it you accept that:
  </p>
  <ul class="disc-points">
    <li>
      <strong>Privacy is protected by design, but not guaranteed.</strong>
      Your files stay on your device; only an aliased, de-identified schema is
      sent to the frontier model — never your raw data. But no software is
      perfectly secure: a bug, the schema that is sent, your own configuration,
      or the third-party AI provider could expose information. Use it with data
      you’re comfortable putting at some risk.
    </li>
    <li>
      <strong>Answers can be wrong.</strong>
      They’re generated by an AI writing and running code over your files —
      don’t rely on them for financial, legal, tax, or medical decisions.
    </li>
    <li>
      <strong>You use it at your own risk.</strong>
      The author is not liable for any loss, exposure, or decision made using
      millfolio.
    </li>
  </ul>
</div>

<style>
  .disclaimer {
    text-align: left;
    color: var(--text-dim);
    font-size: 13.5px;
    line-height: 1.55;
  }
  .disc-title {
    margin: 0 0 10px;
    color: var(--text);
    font-size: 16px;
    font-weight: 700;
  }
  .disc-intro {
    margin: 0 0 10px;
  }
  .disc-points {
    margin: 0;
    padding-left: 18px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .disc-points strong {
    color: var(--text);
  }
  .disclaimer a {
    color: var(--accent);
  }
</style>
